# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import testapp.storage


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Contact')),
            ],
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='headImg',
            field=models.FileField(storage=testapp.storage.ImageStorage(), upload_to='./upload/'),
        ),
    ]
